conceptus/core/urls.py
from django.urls import path
from .views import dashboard, create, editar, deletar

app_name = 'core'
urlpatterns = [
    path('', dashboard, name='dashboard'),
    path('cadastro/', create, name='create'),
    path('editar/<int:pk>/', editar, name='editar'),
    path('deletar/<slug:slug>/', deletar, name='deletar'),
]

conceptus/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('conceptus.core.urls')),
]

conceptus/core/models.py
from django.db import models
from django.core.validators import RegexValidator


class Store(models.Model):
    ATUACAO = (('Alimentos', 'Alimentos'),
               ('Automoveis', 'Automóveis'),
               ('Calçados', 'Calçados'),
               ('Esporte', 'Esporte'),
               ('Móveis', 'Móveis'),
               ('Roupa', 'Roupa'),
               ('Tecnologia', 'Tecnologia'),
               )

    ramo_atuacao = models.CharField(max_length=10, choices=ATUACAO, default='Alimentos')
    nome = models.CharField('Nome', max_length=255)
    slug = models.SlugField('Slug')
    descricao = models.CharField('Descrição', max_length=255)
    contato = models.CharField('Contato', max_length=11, validators=[RegexValidator(r'^\d+$')])

    class Meta:
        ordering = ['nome']
        verbose_name = 'Store'
        verbose_name_plural = 'Stores'

    def __str__(self):
        return self.nome

conceptus/core/forms.py
from django.forms import ModelForm

from conceptus.core.models import Store


class StoreModelForm(ModelForm):

    class Meta:
        model = Store
        fields = '__all__'

conceptus/core/views.py
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.shortcuts import render, resolve_url as r
from django.core.paginator import Paginator, InvalidPage, EmptyPage

from conceptus.core.forms import StoreModelForm
from conceptus.core.models import Store


def dashboard(request):
    valor = request.GET.get('valor')
    if valor:
        stores = Store.objects.filter(nome__contains=valor)

    if not valor:
        stores = Store.objects.all()
        paginator = Paginator(stores, 5)

        page = request.GET.get('page')
        stores = paginator.get_page(page)

    return render(request, 'core/dashboard.html', {'stores': stores})


def create(request):
    if request.method == 'POST':
        form = StoreModelForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Cadastrado com sucesso")
            return HttpResponseRedirect(r('core:create'))
    else:
        form = StoreModelForm()
    return render(request, 'core/cadastro.html', {'form': form})


def editar(request, pk):
    try:
        store = Store.objects.get(pk=pk)
    except Store.DoesNotExist:
        raise ValueError('Error')

    if request.method == 'POST':
        form_store = StoreModelForm(request.POST, instance=store)
        if form_store.is_valid():
            form_store.save()

            messages.success(request, 'Atualização realizada')
            return HttpResponseRedirect(r('core:editar', pk=pk))
    else:
        form_store = StoreModelForm(instance=store)

    return render(request, 'core/editar.html', {'form_store': form_store, 'store': store.slug})


def deletar(request, slug):
    Store.objects.filter(slug=slug).delete()
    messages.success(request, 'Deletado com sucesso')
    return HttpResponseRedirect(r('core:dashboard'))

conceptus/core/templates/core/base.html
<!DOCTYPE html>

{% load static %}

<html lang="pt-br">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Gerência de Notas Fiscais</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/3-col-portfolio.css' %}" rel="stylesheet">

</head>

<body>

<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
        <a class="navbar-brand" href="{% url 'core:dashboard' %}">Store</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'core:dashboard' %}">Home
                        <span class="sr-only">(current)</span>
                    </a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'core:create' %}">Cadastrar
                    </a>
                </li>

            </ul>
        </div>
    </div>
</nav>

<!-- Page Content -->
<div class="container">

    <h1 class="my-4">
        {% block cabecalho %}
        {% endblock cabecalho %}
    </h1>

    {% block content %}
    {% endblock content %}


</div>
<!-- /.container -->



<!-- Bootstrap core JavaScript -->
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
</div>
</body>

</html>

conceptus/core/templates/core/cadastro.html
{% extends 'core/base.html' %}'

{% block cabecalho %} Cadastro {% endblock cabecalho %}

{% block content %}


  {% if messages %}

        {% for message in messages %}

        <div class="alert alert-success">
          {{ message|slice:":0" }}
        </div>

        {% endfor %}

  {% endif %}


<br>
<div class="container">
    <div class="row">

        <div class="col-lg-2"></div>
        <div class="col-lg-8">
            <div class="card">
                <div class="card-header">
                    Store
                </div>
                <div class="card-body">
                    <form action="." method="post">
                        {% csrf_token %}

                        <div class="form-group row">
                            <label class="col-sm-2 col-form-label">{{ form.ramo_atuacao.label }}</label>
                            <div class="col-sm-10">
                                {{ form.ramo_atuacao.errors }}
                                {{ form.ramo_atuacao }}
                            </div>

                            <label class="col-sm-2 col-form-label">{{ form.nome.label }}</label>
                            <div class="col-sm-10">
                                {{ form.nome.errors }}
                                {{ form.nome }}
                            </div>

                            <label  class="col-sm-2 col-form-label">{{ form.descricao.label }}</label>
                            <div class="col-sm-10">
                                {{ form.descricao.errors }}
                                {{ form.descricao }}
                            </div>

                            <label class="col-sm-2 col-form-label">{{ form.contato.label }}</label>
                            <div class="col-sm-10">
                                {{ form.contato.errors }}
                                {{ form.contato }} <small>somente numeros</small>
                            </div>
                            <label  class="col-sm-2 col-form-label">{{ form.slug.label }}</label>
                            <div class="col-sm-10">
                                {{ form.slug.errors }}
                                {{ form.slug }}
                            </div>
                        </div>
                        <br>
                        <button type="submit" class="btn bg-success text-white">Cadastrar</button>
                        <a href="{% url 'core:dashboard' %}" class="btn bg-info text-white">Voltar</a>

                    </form>
                </div>
            </div>


        </div>
    </div>
    <div class="col-lg-2"></div>
</div>


</div>


<!-- /.row -->


{% endblock content %}

conceptus/core/templates/core/dashboard.html
{% extends 'core/base.html' %}'

{% block cabecalho %} Lojas {% endblock cabecalho %}

{% block content %}

<!-- Page Heading -->

{% if messages %}

{% for message in messages %}

<div class="alert alert-danger">
  {{ message|slice:":0" }}
</div>

{% endfor %}

{% endif %}

<!--CAMPOS DE BUSCA-->
<form method="get" action=".">
  {% csrf_token %}

  <div class="input-group">

    <div class="input-group-prepend">
      <button class="btn btn-outline-secondary" type="submit">Buscar</button>
    </div>
    <input type="text" name="valor" placeholder="Buscar por nome" class="form-control">


  </div>
</form>
<!--FIM CAMPOS DE BUSCA-->

<br>
<br>

<div class="row">

  <div class="col-lg text-center">

    <div class="panel-body">
      <div class="table-responsive">
        <table class="table table-bordered">
          <thead>
          <tr>
            <th scope="col">Nome da Loja</th>
            <th scope="col">Ramo de autação</th>
            <th scope="col">Descrição</th>
            <th scope="col">Contato</th>
            <th scope="col">Slug</th>

          </tr>
          </thead>

          {% for store in stores %}

            <tbody>
              <tr>
                <td><a href="{% url 'core:editar' store.pk %}">{{ store.nome }}</a></td>
                <td>{{ store.ramo_atuacao }}</td>
                <td>{{ store.descricao }}</td>
                <td>{{ store.contato }}</td>
                <td>{{ store.slug }}</td>

              </tr>

            </tbody>
          {% endfor %}
        </table>
      </div>
      <!-- /.table-responsive -->
    </div>

    <!-- /.panel-body -->
  </div>
</div>
<!-- /.row -->


 <!-- Pagination -->
    <ul class="pagination justify-content-center"  style="margin-top: 50px">
        <li class="page-item">
          {% if stores.has_previous %}
            <a class="page-link" href="?page={{ stores.previous_page_number }}" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
                <span class="sr-only">Previous</span>
            </a>
          {% endif %}
        </li>

        <li class="page-item">
            <a class="page-link" href="?page=1">1</a>
        </li>
        <li class="page-item">
            <a class="page-link" href="?page=2">2</a>
        </li>
        <li class="page-item">
            <a class="page-link" href="?page=3">3</a>
        </li>
        <li class="page-item">
          {% if stores.has_next %}
            <a class="page-link" href="?page={{ stores.paginator.num_pages }}" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
                <span class="sr-only">Next</span>
            </a>
          {% endif %}
        </li>
    </ul>

{% endblock content %}

conceptus/core/templates/core/editar.html
{% extends 'core/base.html' %}

{% block cabecalho %} Detalhes da Loja {% endblock cabecalho %}

{% block content %}

{% if messages %}

{% for message in messages %}

<div class="alert alert-info">
    {{ message|slice:":0" }}
</div>

{% endfor %}

{% endif %}


<hr>
<br>
<div class="container">
    <div class="row">

        <div class="col-lg-2"></div>
        <div class="col-lg-8">
            <div class="card">
                <div class="card-header">
                    Store
                </div>
                <div class="card-body">
                    <form action="." method="post">
                        {% csrf_token %}

                        <div class="form-group row">
                            <label class="col-sm-2 col-form-label">{{ form_store.ramo_atuacao.label }}</label>
                            <div class="col-sm-10">
                                {{ form_store.ramo_atuacao.errors }}
                                {{ form_store.ramo_atuacao }}
                            </div>

                            <label class="col-sm-2 col-form-label">{{ form_store.nome.label }}</label>
                            <div class="col-sm-10">
                                {{ form_store.nome.errors }}
                                {{ form_store.nome }}
                            </div>

                            <label class="col-sm-2 col-form-label">{{ form_store.descricao.label }}</label>
                            <div class="col-sm-10">
                                {{ form_store.descricao.errors }}
                                {{ form_store.descricao }}
                            </div>

                            <label class="col-sm-2 col-form-label">{{ form_store.contato.label }}</label>
                            <div class="col-sm-10">
                                {{ form_store.contato.errors }}
                                {{ form_store.contato }}
                            </div>
                            <label class="col-sm-2 col-form-label">{{ form_store.slug.label }}</label>
                            <div class="col-sm-10">
                                {{ form_store.slug.errors }}
                                {{ form_store.slug }}
                            </div>
                        </div>
                        <br>
                        <button type="submit" class="btn bg-info text-white">Atualizar</button>
                        <a href="{% url 'core:dashboard' %}"  class="btn btn-warning ">Voltar</a>
                        <a href="{% url 'core:deletar' store %}" type="submit" class="btn btn-danger text-white">Deletar</a>
                    </form>
                </div>
            </div>


        </div>
    </div>
    <div class="col-lg-2"></div>
</div>


</div>


{% endblock content %}